server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 5a1736bc35f4f64b0157f91aea2163fc
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置扫描mapper配置文件
  mapper-locations: classpath:mapper/*.xml